service: name

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    ADDRESS_TABLE_NAME: ${self:provider.stage}-addresses
    DYNAMO_CONFIG: ${file(configs/${self:provider.stage}-dynamodb.yml)}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-dynamodb-seed
  - serverless-offline

functions:
  getAllProducts:
    handler: src/lambdas/getAllProducts.default
    events:
      - http:
          path: products
          method: GET
          cors: true

  createProduct:
    handler: src/lambdas/createProduct.default
    events:
      - http:
          path: products
          method: POST
          cors: true

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        IdentitySource: method.request.header.Authorization
        Name: Cognito
        RestApiId: # API id, ref
          Type: COGNITO_USER_POOLS
        ProviderARNs:
          -  # Cognito ARN

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    migration:
      dir: ./offline
